config/routes.rb
OpenKitchen::Application.routes.draw do 


  resources :venues
  resources :venue_images, :only => [ :create, :destroy]

  root :to => 'home#show'

  # This is here till issue https://github.com/apotonick/apotomo/issues/67 is fixed

  resources :resource_producers

  resources :resources

  resources :users, :only => [] do
    resource :profile, :only => [:edit, :show, :update]
  end

  resources :events do
    member do
      post :invite, :controller => :events, :action => :invite
      get  :ical, :controller => :events, :action => :ical
    end
  end

  resources :invitations do
    collection do
      get 'token/:id', :action => :token, :as => :token
    end
    member do
      post 'mail', :action => :mail, :as => :mail
    end
  end


  match "home" => "home#show"


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :confirmations => "confirmations",
    :registrations => "registrations"
  } 
  devise_scope :user do
    put "confirm_user", :to => "confirmations#confirm_user"
    post "complete_registration", :to => "confirmations#complete_registration"
  end
  

  # Complete the registration
  #match "/users/register", :method => :post, :controller => :users, :action => :register

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
   
  respond_to :html
  


  def edit
    @user = User.find(params[:user_id])
    authorize! :edit, @user
  end
  
  def show
    @user = User.find(params[:user_id])
    authorize! :show, @user
  end

  def update
    @user = User.find(params[:user_id])

    authorize! :update, @user
    @user.transaction do
      @user.update_attributes(params[:user])
#       if avatar_params = params[:user][:avatar]
#         @user.build_assetable_asset do |aa|
#           aa.asset = ImageAsset.new avatar_params        
#         end
#         @user.save!
#       end
    end
    respond_with @user, :location => edit_user_profile_path(@user)
    
  end

end

app/views/profiles/_venues.html.haml
-# @param user
%section.venues.edit#profile_edit_venues_edit{'data-subnav-label' => (Venue.model_name.human :count => 2)}
  %h1=Venue.model_name.human :count => 2
  %table.table.table-striped.table-bordered
    %thead
      %tr 
        %th=Venue.human_attribute_name :name
        %th=Venue.human_attribute_name :address
        %th=UserVenueManagement.human_attribute_name :role
    - user.user_venue_managements.each do |uvm|
      - venue = uvm.venue
      %tbody
        %tr
          %td
            - if can? :edit, uvm.venue
              %a=link_to uvm.venue.name, edit_venue_path(uvm.venue)
            - elsif can? :show, uvm.venue
              %a=link_to uvm.venue.name, venue_path(uvm.venue)
            - else
              =uvm.venue.name

          - if can? :show, uvm.venue
            %td= uvm.venue.full_address
          - else
            %td= uvm.venue.city
          %td= uvm.role
          

app/views/profiles/edit.html.haml
#page_profiles_edit

  - content_for :subnav_header do
    %h1.autofont=t('profile')

  %section.profile.password#profile_edit_password_edit{'data-subnav-label' => User.human_attribute_name(:password)}
    = link_to edit_user_registration_path, :class => "btn btn-danger" do
      %i.icon-lock.icon-white
      = t ".change_password"

  %section.profile.edit#profile_edit_form{'data-subnav-label' => t("edit")}

    = semantic_form_for @user, :url => user_profile_path(@user), :html => { :multipart => true } do |f|
      .row
        = f.inputs do 
          .span5
            = f.input :name
            - autofill = @user.timezone ? nil : 'autofill'
            = f.input :timezone, :as => :time_zone, :input_html => { :class => "timezone #{autofill}" }
            = f.input :cookstars, :as => :select, :collection => 1..5
            %span.avatar
              = profile_avatar_image(@user, :small)
              = f.inputs :attachment, :for => :avatar do |a|
                = a.input :attachment, :as => :file
          .span6
            = f.input :about
      .row
        .span11
          = f.buttons

  = render :partial => 'venues', :locals => {:user => current_user }

  %section#profile_edit_new_venue{'data-subnav-label' => '+', 'data-offset' => '-100'}
    %h1=t ".new_venue"
    = semantic_form_for current_user.venues.build do |f|
      = f.inputs do
        = f.input :name
        = f.submit

app/views/profiles/show.html.haml
#page_profiles_show

  = content_for :subnav_header do
    %h1.autofont=@user.name


  %section.venues.edit#top{'data-subnav-label' => t("top")}
    %h1=@user.name
    .row-fluid
      .span4
        = profile_avatar_image(@user, :medium)
      .span4
        = simple_format @user.about

  = render :partial => 'venues', :locals => {:user => @user }