config/routes.rb
OpenKitchen::Application.routes.draw do 


  resources :venues
  resources :venue_images, :only => [ :create, :destroy]

  root :to => 'home#show'

  # This is here till issue https://github.com/apotonick/apotomo/issues/67 is fixed

  resources :resource_producers

  resources :resources

  resources :users, :only => [] do
    resource :profile, :only => [:edit, :show, :update]
  end

  resources :events do
    member do
      post :invite, :controller => :events, :action => :invite
      get  :ical, :controller => :events, :action => :ical
    end
  end

  resources :invitations do
    collection do
      get 'token/:id', :action => :token, :as => :token
    end
    member do
      post 'mail', :action => :mail, :as => :mail
    end
  end


  match "home" => "home#show"


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :confirmations => "confirmations",
    :registrations => "registrations"
  } 
  devise_scope :user do
    put "confirm_user", :to => "confirmations#confirm_user"
    post "complete_registration", :to => "confirmations#complete_registration"
  end
  

  # Complete the registration
  #match "/users/register", :method => :post, :controller => :users, :action => :register

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                                   :integer         not null, primary key
#  owner_id                             :integer
#  created_at                           :datetime
#  updated_at                           :datetime
#  name                                 :string(255)
#  datetime                             :datetime
#  timezone                             :string(255)
#  description                          :text
#  venue_id                             :integer
#  public                               :boolean         default(FALSE), not null
#  public_seats                         :integer         default(0)
#  automatic_public_invitation_approval :boolean         default(FALSE)
#

class Event < ActiveRecord::Base

  belongs_to :owner, :class_name => "User", :foreign_key => :owner_id

  has_many :assetable_assets, :as => :assetable, :dependent => :destroy
  has_many :event_images, :source => :asset, :through => :assetable_assets, :class_name => "ImageAsset"


  accepts_nested_attributes_for :event_images, :allow_destroy => true
  attr_accessible :event_images

  belongs_to :venue
  validates_presence_of :venue

  # Ensure the user can only add venues they own
  validates_inclusion_of :venue, :in => lambda { |e|
    e.owner.venues
  }

  has_many :invitations, :dependent => :destroy

  has_many :invitees, :through => :invitations, :source => :user

  has_many :resources, :dependent => :destroy

  attr_accessible  :public_seats, :public, :name, :venue_id, :description, :timezone, :datetime

  def public_seats_left
    [0, public_seats - invitations.where{public==true}.count].max
  end

  acts_as_commentable
  include CommentSubscriber

  validates_presence_of :timezone, :name, :datetime

  validates_length_of :name, :maximum => 80

  validates_length_of :description, :maximum => 4096 # characters

  validates_presence_of :owner

  #
  # Public event support
  #

  validates_inclusion_of :public, :in => [true, false]

  validates_numericality_of :public_seats, 
    :greater_than_or_equal_to => 0, 
    :only_integer => true

  validates_inclusion_of :automatic_public_invitation_approval, :in => [true, false]

  # Get the invitation to this event for
  # the specific user or nil if they are
  # not invited
  def invitation_for_user user
    invitations.where{user_id==user.id}.first
  end

  #
  # Ensure the date of the event is always in the
  # timezone of the event
  #
  # TODO test this code. Scary!
  #
  def self.convert_to_timezone tz, dt
    format = '%d/%m/%Y %l:%M %p'
    ActiveSupport::TimeZone[tz].parse dt.try(:strftime, format)
  end

  before_save do
    tz = timezone || "UTC"
    self[:datetime] = Event.convert_to_timezone tz, self[:datetime]
  end

  def datetime
    if self[:datetime]
      tz = timezone || "UTC"
      self[:datetime].in_time_zone(tz)
    end
  end

  def invited? user
      invitations.where{user_id==user.id}.count > 0
  end

  # Owner should be implicityly
  # invited
  after_create do
    invitation = invite owner
    invitation.status = "accepted"
    invitation.save!
    invitation.event.subscribe_to_comments owner
  end


  def self.future_events
    where{datetime > Time.zone.now}
  end

  def self.near location, radius_km
    venues = Venue.near(location, radius_km).map &:id
    joins{venue}.where{venue.id.in venues}.future_events
  end


  def invited? user
    if user
      invitations.where{user_id==user.id}.count > 0
    end
  end

  # Returns the invitation
  # 
  # Guest can be a User object or an
  # email address
  def invite guest, options = {}

    as_public = options.delete :public
    status    = options.delete :status

    # Don't invite twice
    unless invitation = self.invitations.where{user_id==my{guest.id}}.first
      invitation = Invitation.create! do |i|
       i.event = self
       i.user = guest
       i.public = as_public if as_public
       i.public_approved = as_public if as_public
       i.status = status if status
      end
      InviteMailer.deliver_invitation(invitation)
    end

    invitation

  end

  def format_date
    datetime.try(:strftime, Date::DATE_FORMATS[:textual])
  end

  def format_time
    datetime.try(:strftime, Date::DATE_FORMATS[:time_default])
  end

  def format_datetime
    "#{format_date} #{format_time}"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html, :js


  my_events = proc do |events|
    events.where{owner_id==my{current_user.id}}
  end

  public_events = proc do |events|
    events.where{public==true}
  end

  invited_to_events = proc do |events|
    events.joins{invitations}.where{invitations.user_id==my{current_user.id}}
  end

  has_widgets do |root|
    # For /events/:id
    if params[:id]
      root << widget("comments/panel", :comments, :event => @event)
      root << widget(:event_guests, :event => @event )

      root << widget(:image_carousel, :event_images, :assetable => @event, :resource => :event_images)
    else

      # Note the title is looked up under 
      #
      #   public_event.display.*
      #
      # scope
      
      root << widget(:public_events , 
                     'my_events', 
                     :geolocate => false, 
                     :filter => my_events, 
                     :title => :as_host,
                     :past => remember(params[:past]) ) if current_user

      root << widget(:public_events, 
                     'invited_to_events', 
                     :geolocate => false, 
                     :filter => invited_to_events, 
                     :title => :as_guest,
                     :past => remember(params[:past]) ) if current_user

      root << widget(:public_events, 
                     'public_events',
                     :geolocate => true,
                     :filter => public_events, 
                     :title => :as_public,
                     :past => remember(params[:past]) ) 
    end
  end

  load_and_authorize_resource :except => [:index, :ical, :create, :render_event_response]

  # Apotomo entry point
  load_resource :only => :render_event_response

  # These pages have public components
  skip_before_filter :authenticate_user!, :only => [:index, :render_event_response]

  def index
    authorize! :index, Event
    if signed_in?
      @events_as_owner = current_user.events_as_owner
      @events_as_guest = current_user.events_as_guest.where{owner_id != my{current_user.id}}
    end

    render :index
  end

  def new
    @event = current_user.events_as_owner.build
    @event.venue = current_user.venues.first
    if @event.venue
      @event.timezone = @event.venue.timezone
    end
  end
  

  def create

    authorize! :create, Event

    @event = current_user.events_as_owner.create params[:event]
    if @event.valid?
      # TODO i18n this
      flash[:notice] = "Event '#{@event.name}' has been created"
      redirect_to events_path
    else
      render :new
    end
  end

  def update
    @event.attributes = params[:event]
    authorize! :update, @event
    if @event.save
      flash[:info] = t("event.updated")
      redirect_to edit_event_path(@event)
    else
      flash[:error] = @event.errors.full_messages.to_sentence
      @invitation = current_user.invitations.where{event_id==my{@event.id}}.first

      render :edit
    end
  end

  def  edit
    @invitation = current_user.invitations.where{event_id==my{@event.id}}.first
  end

  skip_before_filter :authenticate_user!, :only => :show, :if => lambda { 
    if params[:id]
      @event = Event.find(params[:id])
      @event and @event.public?
    else
      false
    end
  }
  
  def show
    if current_user
      @invitation = current_user.invitations.where{event_id==my{@event.id}}.first
    end
    @venue = @event.venue
    @map = GoogleStaticMap.new(:zoom => 13, :center => @venue.map_location)
    @map.markers << MapMarker.new(:color => "blue", :location => @venue.map_location)
  end

  def invite
    @invitation = @event.invite params[:invite][:email]
    redirect_to edit_event_path(@event)
  end

  # TODO spec this.
  def ical
    require 'icalendar'
    @event = Event.find params[:id]

    authorize! :read, @event

    @calendar = Icalendar::Calendar.new
    event = Icalendar::Event.new
    event.start = @event.datetime.strftime("%Y%m%dT%H%M%S")
    event.end = (@event.datetime+5.hours).strftime("%Y%m%dT%H%M%S")
    event.url = event_url(@event)
    event.summary = @event.name
    event.description = @event.description
    event.location = @event.venue.full_address
    @calendar.add event
    @calendar.publish
    headers['Content-Type'] = "text/calendar; charset=UTF-8"
    render :layout=>false, :text => @calendar.to_ical, :status => :ok

  end

end

app/views/events/_catering.html.haml
%h2 Catering
- @event = _event

-if can?(:edit, @event) 

  .things_to_bring
    = semantic_form_for :new_resource, :url => resources_path , :html => { class: "form-stacked" } do |f|
      = f.inputs do
        = f.input :suggest_something, :label => "Need something?", :input_html => { :value => "", :placeholder=>"10 bread sticks" }
        = f.input :event_id, :as => :hidden, :label => false, :input_html => {:value => @event.id }
      = f.buttons do
        = f.commit_button :label => "add it"

- if @invitation.accepted?
  - @event.resources.each do |resource|
    = render :partial => "resources/resource", :locals => { resource: resource }

app/views/events/_edit.html.haml
- @event = _event

%section.edit_event#edit{'data-subnav-label' => t("event.edit.menu.edit")}

  %h1=t("event.edit.menu.edit")

  .edit_event
    = semantic_form_for @event do |f|
      .row
        .span4
          - disabled = cannot? :edit, @event
          = render :partial => "form", :locals => { :f => f, :event => @event, :disabled => disabled }
        .span7
          - if can? :edit, @event
            = f.input :description, :as => :text
          - else
            = simple_format h(@event.description)




              

app/views/events/_form.html.haml
- @event = event
= f.inputs do
  = f.input :name



  -if @event.venue
    - hint = link_to(Venue.model_name.human, edit_venue_path(@event.venue), 'data-popup' => true)
  -else
    - hint = nil
  = f.input :venue, :collection => current_user.venues, :hint => hint

  = f.input :public
  = f.input :public_seats, 
    :input_html      => { 'data-show-if'   => "input:[name='event[public]']:checkbox",
                          'data-condition' => ':checked',
                          'data-parent'    => 'fieldset' }
    


  -# Manually rolling this as formtastic-bootstrap just
  -# puts text fields in here which is not what I want.
  -# TODO extract the code into a helper
    
  %fieldset.datetime.control-group
    %label(for="event_datetime")=t "attributes.datetime"
    .controls
      .controls
        .date
          = f.date_select :datetime,  :use_short_month => true, :start_year => Time.zone.now.year, :order => [:day, :month, :year]
        .time
          = f.time_select :datetime, 
            :ignore_date => true, 
            :ampm => true,
            :minute_step => 15

  - autofill = @event.timezone ? nil : 'autofill'
  = f.input :timezone, :as => :time_zone, :input_html => { :class => "timezone #{autofill}" }

= f.buttons

app/views/events/_invitation.html.haml
- @event = _event

- if can? :edit, @event
  .invitation
    = semantic_form_for :invite, :url => invite_event_path(@event) , :html => { class: "form-stacked" } do |f|
      = f.inputs do
        = f.input :email, :as => :email, :input_html => { :value => "" }
      = f.buttons do
        = f.commit_button :label => "Invite a guest"

app/views/events/_invitation_status_button.html.haml
-# _invitation
-# _label
-# _status

= semantic_form_for _invitation, :html => { class: "form-stacked" } do |f|
  = f.buttons do
    = f.input :status, :as => :hidden, :label => false, :input_html => { :value => _status }
    = f.commit_button :label => _label

app/views/events/_map.html.haml
-# Parameters
-#

= link_to @venue.google_maps_link, :target => "_blank", :class => "map" do
  = image_tag @map.url
  .external_link
    = t("maps.external_link")

app/views/events/_status.html.haml
- if @event.invited? current_user
  %span#invitation_status
    =t(".change_status_header")


    %a.btn{'data-toggle'=>"modal", :class=>@invitation.status, :href=>"#change_invitation_status"}=t(".#{@invitation.status}")

    .modal.hide.fade.in#change_invitation_status
      .modal-header
        %a.close(data-dismiss="modal") x
        = t(".change_status_header")
      .modal-body
        .btn-group
          - Invitation::STATUSES.each do |status|
            - unless status == "pending"
              - unless @invitation.status == status
                = link_to t(".#{status}"), invitation_url(@invitation, :redirect_to => request.path, :invitation => { :status => status } ), :class => "btn #{status}", :method => :put 

app/views/events/edit.html.haml
- content_for :subnav_header do
  %h1.autofont=@event.name.capitalize

- content_for :subnav_items do
  %li
    = link_to t("show"), event_path(@event)

#edit_event_page
  .sections
    = render :partial => 'edit', :locals => { _event: @event }

    %section#venues_show_photos{'data-subnav-label'=>t(".photos")}
      %h1=t(".photos")
      = render_widget :event_images

    .row-fluid
      .span6
        = render_widget :event_guests

      .span6
        = render_widget :comments

app/views/events/index.html.haml
- content_for :subnav_header do

  %h1.autofont
    =t "activerecord.models.event", :count => 2
    - if params[:past]
      (
      = t("past").capitalize
      )

- content_for :subnav_items do
  %li
    -if params[:past]
      = link_to t("future"), events_path
    -else
      = link_to t("past"), events_path(:past=>true)


- if current_user

  - content_for :subnav_items do 
    %li
      - if can? :create, Event
        = link_to t(".new"), new_event_url, :title => t(".new_title")
      - else
        %a{:href=>"#", 'title' => t(".new_disabled"), 'data-content' => t('.new_disabled_content') }
          = t(".new")

  = render_widget :my_events
  .clearfix

  = render_widget :invited_to_events
  .clearfix

= render_widget :public_events

app/views/events/new.html.haml
%h1=t ".new"

.new_event.row-fluid
  .span5
    = semantic_form_for @event do |f|
      = render :partial => "form", :locals => { :f => f, :event => @event, :disabled => false }

app/views/events/show.html.haml
- content_for :subnav_header do

  %h1.autofont(data-min-font-size=20 data-max-font-size=50)
    = profile_avatar_image @event.owner, :thumb
    =@event.name.capitalize

- content_for :subnav_header2 do
  %h2.autofont(data-min-font-size=20 data-max-font-size=50)
    =link_to @event.owner.name, :url => user_profile_path(@event.owner)
    =link_to "@ #{@event.venue.name}", @event.venue

-if can? :edit, @event
  - content_for :subnav_items do
    %li
      = link_to t("edit"), edit_event_path(@event)


#show_event_page

  .sections

    %section.edit_event#edit{'data-subnav-label' => Event.human_attribute_name(:description)}

      %h1

        %span.datetime
          %a.ical{:href=>ical_event_path(@event), :title => "iCal"}
            = @event.format_date
            = @event.format_time

      .description
        - vi = @event.venue.venue_images.first
        - if vi
          = image_tag vi.attachment.expiring_url(s3_expiry, :small)

      %p= @event.description

      %hr

      = render :partial => 'status'

      .clearfix

      %br

    = render :partial => "venues/address"

    %section#venues_show_photos{'data-subnav-label'=>t(".photos")}
      %h1=t(".photos")
      = render_widget :event_images

    .row-fluid
      .span6
        = render_widget :event_guests

      .span6
        = render_widget :comments