config/routes.rb
OpenKitchen::Application.routes.draw do 


  resources :venues
  resources :venue_images, :only => [ :create, :destroy]

  root :to => 'home#show'

  # This is here till issue https://github.com/apotonick/apotomo/issues/67 is fixed

  resources :resource_producers

  resources :resources

  resources :users, :only => [] do
    resource :profile, :only => [:edit, :show, :update]
  end

  resources :events do
    member do
      post :invite, :controller => :events, :action => :invite
      get  :ical, :controller => :events, :action => :ical
    end
  end

  resources :invitations do
    collection do
      get 'token/:id', :action => :token, :as => :token
    end
    member do
      post 'mail', :action => :mail, :as => :mail
    end
  end


  match "home" => "home#show"


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", 
    :confirmations => "confirmations",
    :registrations => "registrations"
  } 
  devise_scope :user do
    put "confirm_user", :to => "confirmations#confirm_user"
    post "complete_registration", :to => "confirmations#complete_registration"
  end
  

  # Complete the registration
  #match "/users/register", :method => :post, :controller => :users, :action => :register

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Open Kitchen
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = yield :scripts
    = csrf_meta_tags
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    // <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700' rel='stylesheet' type='text/css'>
    

  %body
    -##background_image
    -#  = image_tag "food.jpg"
    #loading
      = image_tag "ajax-loader.gif"
    #navbar.navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-toggle="collapse" data-target=".nav-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar

          =link_to "", root_path, :class=>"brand"

          .nav-collapse
            %ul.nav
              %li 
                = link_to root_path do
                  %i.icon-home.icon-white
                  = t("home")
              %li
                = link_to events_path do
                  %i.icon-time.icon-white
                  = t "activerecord.models.event.other"
              -if user_signed_in?
                  
                -if current_user.confirmed?
                  %li
                    = link_to edit_user_profile_path(current_user) do
                      %i.icon-info-sign.icon-white
                      = t "activerecord.models.profile"

                -else
                  %li#complete_registration_button
                    = form_for current_user, :method=>"post", :url=>complete_registration_path do
                      %input{:type=>'hidden', :name=>"user[email]", :value=>current_user.email}
                      %input{:type=>'submit', :value=>t(".confirm_user")}

                %li
                  = link_to destroy_user_session_path, :method => :delete do
                    %i.icon-off.icon-white
                    = t "devise.links.sign_out"

              -else
                %li.sign_in
                  =link_to new_user_session_path do
                    %i.icon-lock.icon-white
                    = t "devise.links.sign_in"
                %li.sign_up
                  = link_to new_user_registration_path do
                    %i.icon-lock.icon-white
                    = t "devise.links.sign_up"

              %li.dropdown
                %a.dropdown-toggle(href="#" data-toggle="dropdown")
                  %i.icon-flag.icon-white
                  = session[:locale]
                %ul.dropdown-menu
                  %li
                    = link_to "en", url_for(:locale=>"en")
                  %li
                    = link_to "de", url_for(:locale=>"de")

              = yield :navigation
    
    %header.jumbotron.subhead#overview
      - if content_for :subnav_header
        #subnav_header
          .container
            .row
              .span12
                = yield :subnav_header

      - if content_for :subnav_header2
        #subnav_header2
          .container
            .row
              .span12
                = yield :subnav_header2

      - if content_for :subnav_items
        #subnavbar.subnav
          .container
            .row
              .span12
                %ul.nav.nav-pills
                  = yield :subnav_items

        // See subnav-scrollspy.js.coffee
        #subnavbar_padding

    #page
      .container
        = render :partial=> 'common/flashes'

        - if content_for? :content

          = yield :content

        - else

          #page_body
            = yield

          .impressum.well
            %small
              = link_to "http://xtargets.com" do
                .link
                  %h1
                    %small An XTargets Production
                  Design and coding by
                  Brad Phelan

          %section.scroll_buffer
  %footer
    = yield :scripts

app/views/layouts/devise.html.haml
= content_for :content do
  .devise.well
    = yield

= render :template => 'layouts/application'